server:
  port: ${port:8090}
  context-path: /resizephotos

spring:
  data:
    mongodb:
      database: resize-photos
      host: localhost
      port: 27017

management:
  security:
    enabled: false

endpoints:
  shutdown:
    enabled: false

rest:
  config:
    connectTimeout: 300
    readTimeout: 300
    b2wRepository:
      server: http://54.152.221.29
      endpointConsult: /images.json